# ENV=prod
# Look for branch prod

apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-app-prod
spec:
  generators:
  - git:
      repoURL: https://github.com/oreasek/argo-multiple-envs.git
      revision: HEAD
      directories:
      - path: iac/envs/prod/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/oreasek/argo-multiple-envs.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: prod
  
